apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgASycjZr+/n8PXLiQNJKnLglwHmBTqcWbg3dqOGGLbTGPhwmvKYQ9nfFLN5ZMJFK14IKK9/qPp/P4UQJYGw4LC8c8xxywABFNa6wEYki9fZbTBM/HjJXWT+ytEQpj3IJmiuQh+CRlf1+Cq+K7iDJ/ITAE7KZeBAwPltgLXrfKHOcSpckIxeVvez3ATKR7KDxRNSgibTCXCoKo6iq6Nvnpm5OqOAi4wJVKv00K/bX6Sezu/4JBCu+MTEL+y/SYtca0DqV4rcMAvH9KLwIM+2QCTO0raQOSYlq6ewhtCjmnpcu0e8r9My7JwWoUX1/MMbxoQxSuLstQkj8vv5QxVHpwRuhYLNU3wd/oTnwsOuOGGGNhgqs2XjvsJmLIsoTElSK4JM4HxKjhEG/8k1U3HcEx9yphrvyH1m6CPRvuLGEZkNNeXb2xJqgPxboSyzIX3+JBjXkLg8UxKUlie14FQkEbF6pOC2ZhRgWoXPumSWiEAIkemwu8dbIG/aoBGcgDF9ShRu1IiwdFP9yQoa45I0r6dDk3kTKiSiDun7bCK2ns1duYpliH5M4onzAeikxLDl4kEo/L1kz9v/gcQscHj/Ber8jPzKhod2/vDHwNXtY/sF5XDfinCH+qcbC436Z8+5CSlXmnBKRHG43dd+N/4LuA/jSu3U67TsxtXSxjrxj6D05p3VomTWoqYiWLQCeKJAknr1HF9ANA==
    admin-user: AgAWiWyChUoxm1mWahUo8cBdjpAquO6gWv/e/6wvcDB/ygpwScFqYCRlFWKS7e/7IGUgeBVg+gw46z4LH8JEx3IS7lsigwSuIv6sncwSFcQjVxkd3psxHM8/+zWdHpuBzoAZqLOWc+w40xtVk57jFd29FDNKCMSCUZRPgzxX2yymS4HKQA+b3E5z1sfaj5SVpndrflkp+pVTPuSwVftjHv0+rRH2/QQt5yUeQ7VzGbW9qYVtLr63w8BYOytHV7Kmd6SNX6aLBt/EWr75NjzO+IHznUS8Y2tnzyG3yNSLhX8wgZRd1401TYoeZcYMtAeXD8G744sgK9huYMg10xQzLeqQ+WhIsXRlc1lO3GL8JII1M3be0rdp+7GQQ/H9hxrRSgbGy8PM/cVg6z23jPsETSp54DlPTE/vvrg/5Mdloj0BzSgbdgdOBlX4rQhEiT7LaHqCPPkrQjpj9sM8A3iRUQwgAod0STyJhYbSUuLnIMqzTddC26tLV86KloalsNtQB4Jg/+HyBiywaqIFuhkKcSk8MSwS8Xsv+oIQy+g9tt81vVNt2eL0ZHn9shwRTzDQ4O6l57cMAD0T5vD+Y3IcP3u9hhusxs4rEc+oCnMplp2IjGru681Fl+Ga1SGItsOA7zdvm5q3rSk7t0PShdVuTmDfRqr4lvlENHlpO9lhk8NgAgwyzpPRgJrFAiPqgt9e4VxdR1tzZA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

