---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
spec:
  releaseName: ingress-nginx-internal
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "2.15.0"
  values:
    controller:
      ingressClass: nginx-internal
        