---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress-internal
spec:
  releaseName: nginx-ingress-internal
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: nginx-ingress
    version: "2.15.0"
  values:
    controller:
      ingressClass: nginx-internal
        