apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-public
  namespace: external-dns
spec:
  encryptedData:
    ingress-public.yaml: AgBG+VGknTODtTspM071nfZgBbxRHXIA75ttJ7MWClk6u1D8kX+jv3VpQH92mcFRoPevWNfQwC73Ifq4nTW7eR1anw3B5u3ORHEDNNOtSWb9IUl6FOc34SnCoXwv9PGjZKHhPlqc9I1qhjU77Kb/XqB1LvJZjne4rMKYDrOjz94PY5+ECuH8svIVoHRUcTFk2TJ26Wp8JvGmtp3lYoxqWqAU5/eEIXFeYWpLnc98jehTFwQ8Rl4Ese8KlsTghIiVBFvVdXlAOTX8O6D5OVBhm38Cgn2xIFHapADPiBLkyWZJbH1ZV+aEW2uGTS7ynEVqRNjrrul9+0lZ6t4GhkHHW2oG8fPP2kaDrrC7jTaocCYOz0VApBsvvW/YBvvRJT0x8GcvrZK6VHpDNNp6v+tTOL/+GPPuFOfLjOUKZnsZVKJP0r499jNOBS5hveK7TbzxfsfUt0lMorKLQ69Q1mjqHENZ7LJUIiZMbJtzXs/jVsA4gYozs0/oUZA+8/9WtGGTfXAGAbnXU9mg3MPwcMjPxjiNqjm5id+2amLJII9B5zXeAcGRK0LhtbVzMRwMxhP2uHtqq5O8t+K3+36dKIA1HT9lQlmypVieHiu2ObokmC+oen10sQ2fUdOcCUxsA6Y5Bu5VLKDtRMaXduGv/xP1AEGTFwbj6/YALrgDprxywrUFV9esRDIXo7z6TfYTxcxDNHmDw5l2U5/488oEPRc+WWH+zTf3/Av9wmwnEYpz+r8FzE4i8RJgA0ibU0a0E6lXfGjVCnGa0pBLqzQketjr8JBZrMvg+4MJNp86Dg4PXCaQAzf1LHuW1O/WrQwDz8yHfLobX9A67i+KHM9l5WyIpS8K4odLH7hLOAvKF7ixiU5C//PhnbPfBIOb4UNkNQIZxdE9Kf+V8G99zIuMCn5k+emBLTjK/3ohsqFi4PAlneH5iwBJlydUaovuMkYAqk4nvaIODFvSdryQdgwpVkAof6vEoQHZ6JZALSUhZTLRwkXK0VljT9p3l3KgWL0nhDgHloD3QNcfRVCPhpMSTfHnEioZRAPgP7Z37/jUKcSbrYWvRK99okpPU/fPuUupOCXWGwnyDuW7yr8zSpplENXvWnEA5wCNN4uiaBzAp9JkdseOSE7iHjUpgjw53zz8jpvwJIlfkOhEtQmnS0xVyxlkBY6yU5cfyzMQzYW0rf9zZS+PmlwrvklXomNzRIg+ekn25PMud4mcnbxAEdCr4QTXG/KyIpA7d9Vdzy611vKOSXw1k+dIb/wkyo23Mms0dUMTGJb5l6VfmtE3vPF7OU4L+6FVO4H9QDjay78BhhFDHqZb6tMMVl9HiY1uyy2o8ITKJQvSKJaBfEU98UfxBk5BAkmybp2YVBgMfjqy0EsHMeqLXOymzeiAij8P6X7XOK0ZvQ/J6oUrXS0mKgl6VkIkggn22yI80CGJmWVF6y2YP4+bW4McjryA
  template:
    metadata:
      creationTimestamp: null
      name: ingress-public
      namespace: external-dns

