apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-public
  namespace: external-dns
spec:
  encryptedData:
    ingress-public.yaml: AgCm2/PAnFydUMCkRjGO9WWCH4Z5j9NKiYowgrCqSyeFpdZGsz3mCb2W3sCg6V1LDS5+W3t1tgXsm0rHRKeGzGeJqdTLRQ42PbSASqYbYqUfOUgPkxzP2c7Zo6YpSdWP40obxJqrYV3hHsrc7nvIN91weMYjWvEfbdwkhcsKXPSuy3H5emXQOFn2tKhMKVahMaPTaGdaNvCKDEJ9ZJAIbDXzfaD0pZg4FBJxgcAIg2pyqy7+3kEE42O1ka/wpVnlhkc48otTAQdSa7v9+HqfhbBRZCmChroMrxGl+wQxDxPbz95j588ZOhbBXK+IzZhSKVqOW6Q2Ce3zV6GYNmtVDoW5r3JmumfIqUzLqtY7FlhFDUGyMP0lTa47+gFIy3mWQc3oV5+mILCZCLVTXLtFznjc1p1WrxSNsEBbaVOL6amBFypC00Lo0ztpcVUsOdzCG2gKY5Fobp1SedCoY8AXw8nZmmzAc9EcS+5+8G6PhMYAOqpz1VyA2NbqOO5cw1+Ia8tHVO78KYhw6zUzzb7PiVOcdKC447Dk0z3gGZnNGQy4+zhlIKFiH4yKfMgC5DXdDRN96LOWk8YBBBObULUOsLJaSpsn02gWJOloOOnG52sAtqFDpoBLKr2ZJ7ZF2gRlZP0FUniS9LVgs+VHxebTeKXTI8MkUgypApy3TZhWb39x0ZKbbr47slLgOcETHavYH0nC1+CxWGK5Fvrdn3QVhlZdN7bUAhzkC0Ell/AqmQBcoiR9Uv4jUJCdDFJfpJPTqMtVTZ3LryViUuMS7A9/7rgilOHQXSilkAXUjZHRyb+zSTligRWvGEsm3g5Z84NtBnl6bjBOH/m2A0WqVx4fkiT24d+hWgxo2ZN/xm3IuMLYcNbyY9zUohlNHtnXGvaskPV7z0GcKFe7Fqh7QUf2WCy3DsbpxxBVkPnkXVGEpMTfrvjZ+2K9Vg9MXIFYFjdav7jDTcIgYLnO3dxIA0Gj9/wpERfBVf3QHdfPWfpJUXc7VLCxHVUUOd7RE4omi7MF8s68erSOn/cgKLggpZv195joeo+JYrO5MXueO0Eeqfa4UvXwMqMJ8DE/E6KcXbGXhF59uhhy7eDrx52J2nbEB293tNBLxc2CvZ2nMUBAPW36dKM/ulqeZu11cK7yJGiIqXy1IHrZ6aiv8Sf7iCrWPQ3o/QeBaEpQqpiFMe2rvhdM4cObDcT3Ap+7f4jgvITDnUxu9FxjLVueOdc8zBm4lwZ5N4wBRSnlROxh5k1RC85fMEjOTeSCZg3Ebd1tuGSZLqUFubVaNRRnVQms4f2MSJPWiSkrhSVuFOnfmKW1inmyEbi0pQKMMsMg6Y0GndsTDLMhWCsBuNc3zJTBF2So4kIRWb1oj+DLXH7igXoo2hsRx+3K6p+wRLOdCwyjkmtx1xTIyeyuS9oQhJnCoEghaQ8Oe4YyBcjH32qtDE9V5sY/oC7MqWNQ
  template:
    metadata:
      creationTimestamp: null
      name: ingress-public
      namespace: external-dns

