apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-public
  namespace: external-dns
spec:
  encryptedData:
    ingress-public.yaml: AgCmLWYfcio2JuA7abU8kBx6Mh9WFVn3yYFZjRXjU7JSi8cNgkNNO9jTaRL8FzXZ2rOOY7fd0Y+mNwOEYwxEvwgDlncyHDwQcOLq1XoYsfcP3V45S3m+tgjaOQBwdGezUGgfTUW9ZIUhpmfo5kZ6LyNhrGQoFbJvb8Hac8/WnnJrC41e+d1b+mcnripy3fAcfuUACZbh+PSi1S9w6hZrvaR1xjHXm+E+Mtm5hbrMmi2ujFliy7okHB5Wmra8smSi0INQoKqOcHZC5MoYqEAtoSZfeRHG6oQdUEGkjJPDmrldJYlgfgOmqge76H+6p8TI6dUAUD43xIgPqUCF5y5x+4grPdIoaSxBk664r4LRUdtgoG0eM83nZ8bjxo1wWotq3ucCGT0LwaLnaG/p9fwgC6FTNjuC9KPyHR7ndrbCixBk70LAx04gmDHKdLUHTfJgoGUJ98VE3B/7O/1uSmb1mlRzOGQtAPE7gsVf/vwRgiNuD2M5rAF2AMfr2FS3MJzzEVZarX+VaB4ylkBUnMjpEpjXQBCqLNvln/Y0vGEk6AdZplG5AHvCicJa8AnVlspDeYOg1BNiw/aqsxYYTOccoDhWT6WYtDWQB8kw86fODLEbxDCxfvh4HVQ4Q8QHhMfmUEDKEvXGw2hGipYRr/tXW8ZYFoJmzlt9P2G29AObBQKdncsJb9cMFxEHiYYhq2C9zW57g456XmwQPa/IWdv+k2np5tGcgQWu4q4/4WPkGajdDrUQUsSS5cW92G8997kF53R3NwYGPYZRa4fZa2/Du6vIJiXQTg6P2tRXSO0YvXDqOVf3YnNgNXlNIyCPncbvg7yaTJYlBGy9/o6SEWOkZOghYy5gdctULLOuJeTNf1ZaZUjVWYnurIatx385dcY66vIEm+nbcCBxAda1YDz54WjecBjZICCUneiszKCTvMROgPNS+WqLNiTmo+o3MWvW51WKzR+YJkBZzqZZAf7GrUpxLzsSa9PkDlsOF/iajtGRfBnuC0AiLpg+G4NpLhA+TGeL/WHB6pi3ZuQMsYoSmDHK1NerpHnLoVXc1dvbTmDJQ4nb+zU76mrdmfIp/x3IU1GJDGkgJb5p2O/pFATfhfN6wUgp0zZDgguqsKLQkG/hV1GvIqwXWeF1yDjeL+uqx0rTIO8gC3ROq0jAmj4QO9clOvufCHOFA8fSCuf0sN6hZZIzpexP13MNo+EJ/XKPEzkhT/6uMa1ZWXSgHeg5S4q1AvhGbvyc5vuaXd66HSpBtpEQq1lH6kIsJrgcMRpR3Wcd/7Lkbvm0XnklLvIyiKRIm/aj2e5/MJEcA8iu0DLB5nSBIwuoeFkkVz7xIhmOJq5Fdc9+P9LWnlsLZRtp0QNWulXkDcI7Bz2NUzDx4F2o1Hv0qrPJvoZ0g0AuX8G6rtq2y4qwQhn6ax8vsJa6eMTC8zLY2HRaXz2jB66G/3kPnmy9F4Li
  template:
    metadata:
      creationTimestamp: null
      name: ingress-public
      namespace: external-dns

