apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: YWRtaW4=
  passphrase: MWYyZDFlMmU2N2Rm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-kube-msg
  namespace: team3
spec:
  encryptedData:
    msg: AgBxrLwqWnhN98s17w5gzfEkuE1Db2JqwzO3MVznDYsq3zWkZsmsiXdprBL2LGPL9vvlHodPjdjFa3xtLBqvv9Xrxx2nturklhmcw3EKP0cOTeGN2mWZha8U4lZ/YNvCq61stZ6BLqPUfQhTgONba0+rxvnNC4xmWaol67R92dM2PgDlA7WeyD4QF4i+DUNkfUZbGXTDgC/J0kZj5SsZnCrbemWV/QW+1h4JEmUaT9SD4ZjajJP6GCeKP4d/u89cItaKk+JOgjJZxPLaLeQDqOY9oJ2L7ymYU+K0JG42UDeRdMsFjdv3JRNySVFMaRWeiB1tag0xjSNbUsFnV6+uCvnHch0UV/QJ4a96kn2Rtm0qWsCMwbHQ/Hrzhtv80OtHvO7VQeHx9BOHnCnSKNsgfPYm85onF66c/uxim1PQdalBhHrTyM0WAy1W0SEgBepFL91ul3RxN0gDK6oaHC1Q/F2cwZxjANVVlNSaFlurJW7k5iniCzYdLPDOI2lbBDUtjOdYUysnKLokdyf39lP9aBdZa8DPJ4rK1GmpJrIUv/YMQJf771UxaY1NgalV4uFm/hAZ312l24hZRiEr8G8t1wS02BCcAKkCzEdbEE3eWnSZFwRUNoukARa9YnJi/o0yew9FUZR1nEe314PHMW5Zg9WhWRwWSNu/WgvfiBWx48BOi3bCJmuXOHbM79Pp7hBLAyko0Y6WoHcJeuIK4QG6Fa8Hb+47vXucrg==
  template:
    metadata:
      creationTimestamp: null
      name: hello-kube-msg
      namespace: team3
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-kube-helm
  namespace: team3
spec:
  releaseName: hello-kube-helm
  chart:
    repository: https://kube-champ.github.io/helm-charts
    name: stateless-app
    version: "0.1.1"
  values:
    app:
      env:
        - name: "MESSAGE"
          value: "Hello from deployment flux"

    istioVirtualService: true

    istio-virtual-service:
      host: istio.kubechamp.gq
      gateway: istio-system/istio-system-public-gateway

      endpoints:
        - uri: /hello-kube
          destinationPort: 80
          destinationHost: hello-kube-helm
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes
  namespace: team3
  annotations:
    kubernetes.io/ingress.class: "istio"
    external-dns.alpha.kubernetes.io/hostname: hellokube.kubechamp.gq
    external-dns.alpha.kubernetes.io/target: istio.kubechamp.gq
spec:
  rules:
  - host: istio.kubechamp.gq
    http:
      paths:
      - backend:
          serviceName: hello-kubernetes
          servicePort: 5000
        path: /hello
