---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-client
  namespace: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-master
  namespace: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-data
  namespace: logging
