---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: eventrouter
spec:
  chart:
    repository: https://ingsreinstoredev.azurecr.io/helm/v1/repo/
    name: eventrouter
    version: "0.2.0"