---
## docs: using values from secrets: https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/
## docs: generate the sealedSecret value: https://github.com/fluxcd/helm-operator-get-started#managing-kubernetes-secrets
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: external-dns
    version: "2.20.4"
  values: 
    provider: azure
  valuesFrom:
  - secretKeyRef:
      name: ext-dns-creds
      namespace: dev
      key: ext-dns-creds.yaml
      optional: true