apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: ClusterRole
  name: rbac-team
  apiGroup: rbac.authorization.k8s.io
