---
resources:
- namespace.yaml
- opa.yaml

configMapGenerator:
- name: opa-default-system-main
  namespace: opa
  files:
  - policies/main.rego

- name: istio
  namespace: opa
  files:
  - policies/istio.rego

generatorOptions:
  disableNameSuffixHash: true
  labels:
    openpolicyagent.org/policy: rego
