---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper
spec:
  # releaseName: gatekeeper
  # chart:
  #   git: https://github.com/open-policy-agent/gatekeeper.git
  #   ref: master
  #   path: charts/gatekeeper
  #   version: "v3.1.0-beta.9"
  chart:
    repository: https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/charts/gatekeeper
    name: gatekeeper
    version: "v3.1.0-beta.9"
  values:
    image:
      repository: quay.io/open-policy-agent/gatekeeper
      release: "v3.1.0-beta.9"
      pullPolicy: "IfNotPresent"

    replicas: 2
    auditInterval: 60
    constraintViolationsLimit: 20
    auditFromCache: false