apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
spec:
  values:
    git:
      url: git@github.com:kube-champ/fluxcd-multi-tenancy-team1
      path: "deployment2"
      pollInterval: "1m"
    allowedNamespaces:
      - team3
    serviceAccount:
      name: team3