apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-public
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-public.yaml: AgCzKhuNYRwd1qABNnkkpN1Ar3vwdsW6HabARZHJKaIepsq/UOc8GLih73nqiEVyLK7udnmdgc/CNKbg8yELkd6qmE+Sr1ATcQC8a+q+NDmhTHSDUlZBeTgN8snV97TlDgU9172e+TZY659JvucIt+9cYu+l0N68qUH6L9stQT7WYWYj0ftO6Aw+VwNEKOb4VzsmW9RCgd6+oxkN463xf2GANWC/Reutp/WgC2FoSwnbnl5fmj3XG6HZADrBUxwuw1B23ngekVlPbTg4977+hlTOH1aRw+M50bY02MirrgTFBCJjAmHHOo8YymWDuP0VDPRV3cVsEt8FH5sbFN0VgH0dh76oGMxyTzCAt5fhozHWuZMUS8VXPu45aHDnptwJxmFkOV0ovzdiHSAAK9GiljiJoTnt/kABFcr5ZECRIEF9agRWA+qGhwjMd41FUdZ4JCJ0vcoNaaB3EeQN0qtkGEfkKCr1b5fBiqLTShawYRrQ/fT20FMhgQAUWewq7mCZGvASOSAuhwi2j6/75cXL8hwyMp0VG1Q7nj91XyDrCJq/iZB/ajmM9Rioifa6YOA8uICGefGxMvqPeOkoy15gFwucP4vRSaXpaAgHXtpcr0fh+Q9y2K5jKZPidgV7ZBnXm2WB3hr6EG28KAh+aGUVE+3sPUc4dc+VJm4sVIolzRVeCN/BwBK2tKm/WdGvFQkv+8m6HXumb3jLlw1ke+o55jeYc4hQtn80T0BfAV9XxgYaWm9w3Zz6lZ4akVLDLIVXpB44hzZqCPe/48UzocCvo8iG14NDqHa+hPmWA5ZdyNi5RcRVueUDeopTOqJfe2Oj98X71I5YRa2ojc4ZjIdmmbqmL8SJZH3OU1fBpQvMb6cKY1TY3oyOQZNTucvHRnKU7ewSjvra+o+PxrbQAOjXN+yTA0bBFVrGE91J6OaB9/rS1wu72CBc8BpB+rrwA7wHKfpV6m3zXn0DwJYTJYG0UABAaaehV4YZYk9l5rhyw0sFb+NbUjHpPiTyYnjsgrwzGE3FWDOnfT71Lf/mjWDS6rTB4HaygpxIMyZ3IVeORzrThWdlibO/a8IQw4H7R/PI1iidkl3hOv9hX1jSPeUb4C2cIeyAjBo/JsLfEkOqMsSu5Bma4YKUr4UcIPbgRrDTy67MegyXy29MnVBvGYFHuivgEy9+nlo0wJlGz7vNRcpMcuFL3ug26XnXTii9I42tCgtDLi+Vf1wXse2hnS7nfwYkJ3+IOUfmdKKRteBpGvnT0L5nIxzTPsi2LB+oDhRf/xKDw7Zp5wCgi/SRS86ATQoQhFBNxcQiWLhbnXc/QHUuRW8heKqlaC35bhW8BugbpAYcWiKLj/htjNCZbonNfEn5foj5vdqIBlkV4K6/PnTB
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-public
      namespace: external-dns

