apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-public
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-public.yaml: AgBr522KXO4+kt21fh9e2249o7gx7pysYyXG0GnCVvObcvXGXGWAvI6nozZjy9fpSmDeJcxNcP6fI84uEiUaH7KKOe5EPYlzsAGpF6OnpMVy+kk6mJbLWYwsrvAl1tqDZ2DWSEqvWq8P/imkfrr6+VCJOyTAnUmMt+F8wOm7OBOux+g7NG1tuW7+fct4A3crSjhwmfaY8IbyBrc8RDQ6hwHQUMl34/uQZso5zMQzylKzhXtwca9/qpaS0n8BSTY8nfYcWxM1V7EWzOGn6Q2WiAbm13QDjxGnxRC25NOEAIbUoPZNdsxcqIaVWoZw7bj0jr2wiWQmpKSlCMmqYNmts0aME8zr+WA7LKz7hJVG8jZEn59vB7quAbDidPcvIDGT9HXq4SOt8ygQHqPUj8bK3NnTIL4gcNdueBZFbEP7x6qgYVCODhYoSfiBW6Rxj5E1Ir2f6ns8tTuycV/8Ou21q1WzfrHHD0emPH02v/oX8q3z5YxaY431iCOcTjzYW66g5nLFNAGyXY6Mu43XqJsLVMCz85UvIcxgR31APQieVui5YA+6pKT4N/WTKY3oGX6zfMDj7XeLA3u3OkUbg1+VIe7k48wPP4/Rckv+W6P7hLs+gK9D6X0TodFzSy911NJEvNzPTVVTJQZn4lnZlmWbW/Bt1+EsH5+OGEX7mHo8guoPXepHqi3TWhJxZxa27uAwjPBqAu/QPqGodnWHQiQV6EvdHDpXClx84gXknAPYU12x7L/7mhb+/b4g/0wbanBj+IJBUBonkAgWHdECEJ9x644I521F3zgIUhz3cfEpNv+sdnJlaQl06DRCOWJvknjIDxyTR1kNxYme03B0m3rQX3Q5sNxEBNEYamnHKUjFNlWar/jTnDtRBfg1md4+ArnIieun88A4XQUyZ7jawNhjiExBLzIvz5R7+EFAv/tAi+ryvvlIbLewio6V9Tpb74DaeBxmMplxh7eDQrhNiS38jV/VKk7s/K3SeLRwwrglhtgW7Ne7erm1TQO2iHHfMamuWCCTOvSyvPpq8Os2oS3N+vOYgIqj0D6guFiR+cRX5Xq5Lfesk8d7gGfLq0BpdLGia0bOFh1/4CZ92i20yuSOb6ErnLR2VAEbwJPA0ahzGlKFi3HwGxsp1xWwwidJTV0343FOQi5kcoaNR23alZzDUVn+r7UAAHHnfE1GrUOU9V6dg+2RX5P4AxwprXJewOygIuL4xUk/3XI5KS+pwkpxhh5JNZwyDU1p8R4Bas+PG8pD9wlqPYwapgU9KzOXUSepfgTTgZzgJvQk0i090ze1u3NbFWK7fMkzTqQKuOszxUMY7yyL0DrHEXOHTwa+vLoqOs7LQ9HMX1d5LYBtSN15M+mlRl9Dgsdetro7Ng9qbK4Q
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-public
      namespace: external-dns

