apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-public
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-public.yaml: AgBZ1RX4TKnowusZgLIoCdF1QtCiXl+GSv4cs2iN8whh9iRvNXqiFLW1r9m5CTEc4M/0Qgr1Q7vPVeNCzNHBrjm1pEI0gqa0c8AWOVXQ7YUkapaCObiVZAOEtzOBhKZgFSTkwX66+O6ZcMKHB4+g6lm6VGIYlISi4eholW5YELcWjFK89JhrdBie/mRkgOBOgR0LI/ZuER8IVKvlT4znWKFrhUkAN+IxEk3ppFSPnAAJkEgmvG/m23d3VPFF6BnC4zUBup5ud0H97bTlUOolIMzhcPzZBCiDt38hmS9WZMj0mcPzuAfuIyFqLiULmFTvmpGQjFvqzoXWhUsJfx02/AfpUDd7VmOAMug1vaoUPcVzJb9ylDDrIoFwGlNGwDqH0o1iJcGKe4yJiWViOsY6gnNfQYOrnARvOcvY6MXXvQia7n166X08HflLdx5MRVzA/zv3yrYBbH82uNF+cAfkvYyWM5D9/pC9fGkuXlRMPEAvSk8nwbvPJGmvnZAIJO2F9hhmXCEOsjlgeQsK66lhCl6TYnJKa+juKxjJ97L7dGYa/6Mw9henTT6mqeVz+8m70r6tj6KpSt9QTw3g3+OoVWoZRwUOmYZZW9jlMu2Xr+ocib6nWyjlQjbFL283EilS+9Z66PDN3K9H150Rck5zeZLLvu2M3NMUj1poyw6XmHneXhLM4wAjA3eP9ZQUV2XKqiIvpAY5ytmTj9KqmJxhtiOCIN4xdkcVtuh8UZhZL1rpmQe7iaz2kMIg6RFCijfYYAC3yS0iirpR+uQxj2ZVsuHttlxFJnqe5XwPD+795lQZo51OQ0Z+jWO3yRecK9ESpTXS15NKtqk6suu5TlH9dUW3eaxOBsOsJnjv0fw/0WJl1jzNqOlDSi/jfORJyMVMGkHv5mTXGwyaoHjZAiuIWeg8ic8La5CWsxKpCqX0mi6ETgvBWXmFqTy+ISWE0DhwF01i0dSe4EGRyiRdf+13YZg09omN9axsicaSKoTc6FSCC+N53UnGasaQb51F2q/okeRyiqgQigs5t15ja/JicpP9+mBBQAD4/SXzAf5ilReEjVlFGcRStvLDbfM46z6hxZc1k+vTBkmutxDV8sksjeR40mX2DQXg2XzXBISJE2+y1u32OKjfd8dQd6yQxLb1z1ZQXe13zFXpA/6dMSVfqKqO3RNkBJzA8gjIsO5mgiEuv/oyQW+mfyuuDH9ELov6WuyX7uDJJqJWa25o62LT6YIlJDCYHF61vU6siiMVGajAjOd4cPRTh9zMpAeaGJKlWxdSNwtzkDB2AV4Igp80c1cuAhDTZE3MBouERQGZ8CxKpq7YC2T0C2tdP3Xea8r3h5F1xaAihoWQy1tPuSr6vxrb6hagE5x+tztCmX6N/zPi
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-public
      namespace: external-dns

