apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-public
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-public.yaml: AgBKo/B6xt+3lb2qfVVeNbWEUmV7dSc8TKIrPsZI/BwQG8Xu5NyN8kVZm/VHEnS6Xpgt7npyGK5W7OL2UHIjPivVMFKA3YSNQhbfcxOqznJPfZzfPsO7u8vNwMsayKvG9P7/K9I1+5+oydeWAI271bvk6BntlRDbctwryDuEHVlArwPBHPtMQJ/upX7lMk8jR8V0nwV/dfwfkOAega4RYaXvBTrI9cWD1Omz/QGrGD0FXjWdroGomoNOmDa1aq+oRY0D6UJeIyfOh29S1jg6aci7G3Rt14ER1wWPTJTz3yb0faPEwhPT/E6iMT27x+qWiW+Z8FjPrhscgwxkSnF6Qz8/havwJgFI+RWQK57tEjjBc1A2PoYCUtZXWoZlqu1ubR7UK5PpecKjf2WVJdSw9LEVCbtG2y3CQ0x6YJHzN5HsEwF8E0+QeaHr/CUasl97CAt6k6H+tGvJux/o2bivxkZRje7AY+vpbYyhHZIMcsu6xTzfUdHiMfvR/QNvG2B/uJjaksBIywZskh2sT0erTU5O21VPPzB2OlzZSv4zUAX4q0hK9yYvVzjAZU6RSLpmeAxgjP1B69ZS0oODoga4ORzNqE/rChpEEYBFrvemUOkcrFNpl0BqAAXJs5grovcKc3WEwwLrV1pUo05QwRihXBKah4ZKoHuTOydaXXGmzHADdB2NyDzMd/DRiYJcVNNlOJU14aLDKCSSf6lX/6PyluqbadebCkBuqjjY67oiWZ17hCtGKVR00fiKH0Ja4AEDwrh9FR23CnJrn6uyBAwSGK/bLZ0JgGbmmMvcSwCHMpxRG0JiEjWZ7/z1xmZKMELLmVD7VO3eUg57V63GNL6u4qSrOPAy79m5MGk4EE88+2GzdFfoCGDMLdvEs0WoNmb7R9qU4TqWpGC069ZYNMEIJk3dkK6kXWeWO7iBjYLAsYQAOyXQQf9HOVZGx5euWXe5IqIeWBAvM9oggF061SgzSn70N/yfy/HRSGr+5J2oTfjhYYY9guwwLtXKb4RjfxLthD5ZgAzy/2LpV2/w8v+cOOu1XIkcmWuxDQiAxTR4s4iUn0mQpHzcX8Mi+CiW86Mme6Y40TYz/psXzEhgV1SpPjk+czEQsm90XyHZcFD4ZIsdlVrmbxzmGsxlPa3fMcE506Yh5gFiMGke5ImmW0yZghQdAv8LP4+DCosGAxQJdKMSeJ/Yz7sOrC9cBUW97DTfmIv1dVegK5UF1eXuX/8Xan9PgRMfKPpD5ld1IXbd+qOHXndFE4v0zmHZX7YxV6wdK20ljVsSSZn3QPMDYL2fJJ8z+4xn/LnkQY/7t2cDjnZ3IAi89Ni62c+Q0fYTi94OcI8feKYm6paHMdL7zT2snZb39tjlEw+rsvraJkPCCGCj
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-public
      namespace: external-dns

