---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali-operator
spec:
  chart:
    repository: https://kiali.org/helm-charts/
    name: kiali-operator
    version: 1.22.1
  values:
    cr:
      namespace: istio-system
      create: true
