---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  releaseName: kube-state-metrics
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kube-state-metrics
    version: "2.9.2"
  values:
    prometheus:
      monitor:
        enabled: true
    serviceAccount:
      create: true
      name: kube-state-metrics
    namespace: default
    namespaceOverride: default