---
## docs: using values from secrets: https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/
## docs: generate the sealedSecret value: https://github.com/fluxcd/helm-operator-get-started#managing-kubernetes-secrets
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: PLACEHOLDER
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: external-dns
    version: "2.20.4"
  values:
    image:
      registry: docker.io
      repository: bitnami/external-dns
      tag: 0.7.0-debian-10-r0
  valuesFrom:
  - secretKeyRef:
      name: PLACEHOLDER
      namespace: external-dns
      key: PLACEHOLDER.yaml
      optional: true
