---
## docs: using values from secrets: https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/
## docs: generate the sealedSecret value: https://github.com/fluxcd/helm-operator-get-started#managing-kubernetes-secrets
## Charts here: https://github.com/bitnami/charts/tree/master/bitnami
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: PLACEHOLDER
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: "3.2.3"
  values:
    image:
      registry: docker.io
      repository: bitnami/external-dns
      tag: 0.7.2-debian-10-r21
  valuesFrom:
  - secretKeyRef:
      name: PLACEHOLDER
      namespace: external-dns
      key: PLACEHOLDER.yaml
      optional: true
