apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    prometheus: k8s
spec:
  version: v2.18.2
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: monitoring-prometheus-oper-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: web
  baseImage: quay.io/prometheus/prometheus
  replicas: 1