apiVersion: v1
kind: Namespace
metadata:
  name: test123
  labels:
    gatekeeperProfile: none
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation
  namespace: test123
  labels:
    app: nginx-privilege-escalation
    # owner: devops
spec:
  containers:
  - name: nginx
    image: nginx