apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-credentials
  namespace: external-dns
spec:
  encryptedData:
    external-dns-credentials.yaml: AgCsMN05w86U88Qj3UWGRZEb5eUlB+hq5t8NyrfAgfnW+tnk5xtrrsBXtH5peCa/FRe6Nh8Y7d/l26NvbAs27HW3RhoBArfEv0PlEBTA1k0eti4AUzAZ+0fiVPxqHOE+BLFHXvu6iBclRNLADHR/xqvPdXthnA7vgEqOm700hEL4eR64scoRrQg8pKwnSVDWigXqUg4dVosvjj7OqQiS10WeYuwVK+NRxWRxb2M/GtKsNbOUcYaWVUl9Ou9Yw+8NfdnaoD0nq+pCG3RNvkov6EZWC+Txh3oVJP2ct5PthpmMx6dWf+BFyhahM2c/P5Ngq2oYU5TOZNg2GMPyPXjslmL+ik/ditkiTLtQOXeh2HN/9K2VHXPUIThTS4eROZUugopTEmLxAGvfn/qpWwPD5C/WOqdYJwHjbZCeuJtmfKqbWbDBOTYSDTR1g7tuBrpX224OpHGbWOgTnzmMWRGCR/L9TkUqSlRj5PJRtN3GS4R2noT91M1aIPUglcwt209suxtYR1sdQe6fz2jPSVi4mtgfUs+ZMlnwthoFWhXVShXGkDzC+ON+OeZVNxvSvoEn2S1O1W0oNX7RtT+00LLu8OLiW7Aidk4Sv3gUtisWF/aoqdypsOpj1U0gW/HsBweqNubvcbvwQR+TdPuUwuP8mjvcooSqTHS3LhRJJrJv/IE7K8JaVJJh8KmjOJ5bAcAkcY3dqg0JgEBjxwsD8mSWdVpmr4othA7lzhr17wPzUu5yv2R+lRyWwENXVBLW6GqD4iv5sWN7Mh4rmYLmoJpBzL5PsdafcZsHB83KgrKlnsdhLIpM1IbnClbUyZoPCT+iCW/aAkNFuqfXe21ofKKfoG4LLUpfNoTPYIABy+DPfQdg2y7giIuVT82FuwROrtR6A5Ik1cJvPe/pKCupU4Btlb90UY3WBJUwLlRDbCNPaXDJGmt6p5l/lSnOduB1hm6YO4hLo0pMAqL3LMrhJqGuKunjC+gMYZUV9qYMQkHvEsQVTQ==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-credentials
      namespace: external-dns

