apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCju4vXJxL8L24OUcVRP8sho1lZbcq+pn566RjG6kLr9MAR9hr4q8cW73qvCBOEW+DYuUCtCRghul6TrEw90oDrruPSsnnAHJDYqkxMKWoxapm2dZ11IL2Ui11HyG6RfWsjwbLIQudiFr+t1UqzgORIS1oJ5KkzEefLwfvI2RuBK8pYgVWF3jCVtlM5wQcST5u7r0HF80x9vkLuVP4nqueIih1oj4GIkx77ATceHHDIOor9T+LAf+RGYXqQt9+355LwkHo0+K8fdBUR9giHRHaM4LCUJCGLxXXALwLrwp8r3QDUC/vvxJqIPf+kWe7Evt4h8pjO4pC/NHM6Y4G+RAPsapWNuomZOlYFq3aNqqQDLsPruofdFCjHK5zbe5J+a+/sagNe5Ph1GZ8O+cCrNR/MRRy/4BQtuvQ5QLmxYYq4CkevHNevsno5avTQ85bSxn73DGtb00G2egdE0Mp6Dr6eGgFM/DJeebe6Y7ebyIKxWrl9CQVR62d53AoJo36bzea0tAu6RszAQpJmk6DtyEc4mHJ+Mo9wdulTHtQo9JztP3uNLOnaCSxPyfJGMayR2VT/H4GUf061jkekJRKMbyf2qoAfw1p96Mr5h8+DYpQLJ3kliaGUVSgKwM4hg+Tg/c3ft1s52ZuAmX49UJ+hw4cDWhi5XPE4nhIAJjvDdAGB8mGFe0wfR8oqf7Y4n/szdBkhJYBZE/9y1A==
    admin-user: AgBgJoomy3Sd21A3DZvzLO+1UGrzz74GyWNHmq2frHUfF/YD5r0CzdkaaJOJ/ceExY+3Sy6pLBO5bptDDBd6/ypgBVD6HNk6M9qDfswA8fkv5vvCFWd2VdREQSlFXr0Mf+vneZRZkUwy3aqBAp0oDZFhzka8q7+UnfM9sMmFNZTB+HQDrHMVA45qzQFynMuxc/AfBRHPLhoPlKqGYTbjlCL/ciYnGB4fkEriziPObilEZFBM0NR71pOMG023/wuysyJMVILyl4Yk7Aobeeyi4ib5PDrTfwc5fHoY8Bd3uhllFZSvxrWGwKJZ62wgg5XDz8+tdpMShf2h6jGFIoEYz1HOvUXYrzjgyS7mX1Y3uiHpWTWn1dbE/tpdrh20EjciBP5Z3OfLpzOoW0sakXA/lnOcaadlPaMymqukTjcZ9AtVhfPQt4yiaK6NJvIyEWYBvQeaiCqgYYoMR6igJsTJ28BrtNMTZKIql3pNXJ8s/Pf7gxJ2o0jFUsVKwdcHA2TaUR+m0pXBXg8GMlMTdi4LheiwkiHNvUTZrfGWef6WmpAaega1aKOp7ooqgAjr+jyC/es13QXCOQ8KDyI+tgA6RQcEwgNFuv4oCKJdReOJTfI+MhdplAibWiwDdxGc5RMpuQzhl2Y+ArBQeYFOBW9Rd1X2DydA5s1AmUbYsukNNv14fxVMNvAUe0WQEEF3+qgH7EWAknK25A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

