apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA4gSrVCyyozkNZ3OARdU6IeAI5U8SE3SobQODUvZ7OlY2jUxBXX+Ww5Uy+tf8TueArjwsHPbvz/PPJav7pjvxxsz9zsFesTjkM3A+3nAO0BmsnUxf7WfvviUWOhHWE2BEn9YeLTFPPvnxWiz/5lnLqLzMhpBt0znsfmqrwbkq5/QsB8vQGfoG+4e2q4/Ykq2H9fAN7N8fP0d2uXPkMzGoEbQR6olGeOBeZ5wfcVQaXKg6UEv8N4bi2bn85VbA+OVlhxvF95QzvZiqCEAJO/egAcavwaLvvgUKSNGAn64+q4CDPBcHq1tn8uTHapTtDW+2AKz2BWFrYGC9MHsrc42uRbMnA9/swmJvdY6rpVUBHmgk83nO0UiiX99UvlUwk7HkZfN8DS4VzHSKEAGxYgMyqSe0Pj3/6gHVZivcmpPpDBHEgqUvH1p5rzDbmvcPNoBAJd2o2PcJr+wMkDK6rQbgNI+gT77Qz1amsxCUG141CcgkSVCFhhfJsKpUDj/jk6GfN/gRmOO9Qwip6wqYpHeoCC5ce4mvbSq63SG+xPrNj+8ASSFKN+LqnOMJAQdRDM8jU0EyTro5q7JIOGYmiTuhA08NidIQ/7Y4pqwDcw4UN3eWLgXhq1LimEekvszN5iBSltO3R+b4G/bamajM9I4dsiE3bReWnNAyHML7LjoHloowSHRVsXXinhfOScecx3sX47/1PGlAjOw==
    admin-user: AgBwRLzrjaUJETWcPVwjEkCplrnF9pS0ukCiAci7Q4z++9jiklz0dS4RoiqRtMoU8c6XfAUaVPwZHQK8sQld2fZ4EAKNLpqDvuPQKkB81pJdQUeKnLXtxPaPo0moZjt29So8os90ydUzcQnKzLbrBtpoU/feSS+V7+1wcyqsKfSGIqvqv2gvjnu3O06BQ5oXyB6O9qg6lGVpKH5kTDV3AiS7hS1zQjTczVvYv/m49qpquwaqcH8WXHLvt/He+TEwFtMjsbSjKPl459kNuokP9gDW9Ko/7qqz6dHUevkyTXsIF4pxtuG7nFclev+dO8vyM2Qq1s77hRfOeTxZdiHAR4hXoDJu7NDweMvGMpCeI7w+KJPIQg2jInPuY00L4iZwRpCrDzJr0yrkBCA9V8NmXTZIb0YL9qG39Kb8v8j8IW8y/i568tI0sONQPpV4LllqaVm2mwZZtxQxBo96flZG8EsSDa84O3NPUY21ZtX+4hdEdvYfGU+XFfjaTIu9PxVs//pU7VMWiuqNBIetkgX87d8yHMd9jaBI4PXcUmlLT5cqQLeNof84fanU9sGodHEcGj9gam5k7l7LJZsKs3GuyRgLnyzKk69/Ix9/mKwsWLKDYTuIZL9oOXjKcmTo+bGBiaOY4rQpD0mBgasEJfV4DWZumSRTvwleAR9VVEi7itXjv4Y6YN86DU+yJ1C8QyPHxLIuex5U6A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

