apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBt8KDwyb00HErx32ZURcskGRjtS6hJcxM47+NEhu6IjloEvUlECoYJeNLXQJIikj5JSIFcvRO2QMDkuDbGW9KkyJeU/ZKuOLMFI089DblCJeCLgLbzeej3vNCBFJYjuXRIFOaTTTE2MQGQd0tIiq1QfnH0zsEupM31+GaUbVcbS4ZrxggV9g2YeA7E9QT68OmDgwbk9kpbmOCrO+OG0fXlPTkU5+WnfrrYrVTPL+84YWjDPEqKTB/SZ9cPQaJXZiutMdmXSlhQlsgpPWfpJWRFgRFHpayaw7tJeTqeHdKz2inqt7CfQ3UyK7zrLmHicth72d4+CpSmfFHsd9Kk0atpKS3o1qiyzF++leOYEd0ts7RW3OJjgjCBmLNU1/kNm7tLL5VbkW4CgXImEbMv9rXG2AycVYdZ03P2l/bhV6IhGiFUL92n3pGglaQttVSpgl+hcNCLUurXK/8OWpI5I7qUnOAafN0HIrnEKg+0fJRjPsufCzfvNcuDujwjOxHo8uL/Pp4buZFYrnFszoi4DrgH5+LiYhQJA0Ly8ZafE45vjPypaFTcoAn8c1VdDbmpvA2TESKALChn+KQYutwSd8gYB+izMEejCqD4xGe/UrlC7orlJyfB6w2IJ38eCfcqRFz32t3uhhbfGsEsZdNuHNBQAh2oh00Lkkt4RJPssb6S1tS5iO8fQn3jZcF4DQdhyOrgTdxE2NBiiQ==
    admin-user: AgBfx89byYCiQgzg8bq8UozDqyk5iSETqRCsUj4f+uqImYV3+6q0+yAKRWpQRUAAJbvxdV91QujHbd2OMwia+E9ats2fJ9Ve6mDXee21zQhIdRdxMSiQaCfBOs5NVRFBKUyAjyB3XreQLonimpdNm3L2mPPS4rKofxocTnwsTrQh455a6MYL9Z2rMo4ha+VczmIJ7j7J3xQ9lnxfITzl5J4c/ZW99oZlSoeAbG4aDWO9Ijr2P4xS7JuopJry9Pi89j4II7lquY1xCM0/xPhhidqbeHk/DCTnYf70gvcEHsCfbtjQheUf7e4WHKCmWNgDt/2lWulp8zO8MCgahCqBiaQls5J7wiVzWEeyzvNpT6G87DAfvC6pT5ZKQW89dNnZoaqBhSyHYQQ3QCP5EGIzHl31iVOkmCKFvFkXsHhl4zID1dGjDWeC37PefvwfXUq3MF+afHG4DSD0v+3EX2MuR8GK4mANRUIb2d97cdlwS7DDliL5Q0EErsB0qyrxbeK50LvSIfIqmhKZIsyU+d47uBmi2CdrndWUjNqE0KY0/kSLN5bTDM2em39TJQjBJVfYvt9VKHn2ivTd9Ax6poq/qhbrAfkF8eDXTNfHG+YoSnVuNtkKFVNTgyv6J5k/zAa6ji91tqbVKzACuynQrAJ4C+KRj7o7sjjaRWoOZCLnhuuy0Tl0fZtUvIvIy7oJHn24ozQVtBXNcg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

