apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAknA5WS8bwxq9pAT5fQ1ZGjlFy/2He+6xmziYkrSii630IrR6j3zqfkUjsy6wtzeust8YkhqQkVbuNQrOMG6YO3TTgF692crMGIC8rdebl/JkinWg+bwq/rgdBA+44fDAgMCkk0/i+Vi//GzI+y/vv/2cgfJq2EotWK4MHttw4bonX1gCuYgcPjEBqYqnER8esJlTgCu++9HZoSJ9RfmLeVnxJNkU0EB4nmGN0IdAXkPzwAtZ02NTf351VHjqw8iKuV9kOKzoMTuDBkQzIHMK9GvCfd5HLRp44NcvJOO40pXS0IfQpZ5eQmjKvGBMpqpJ35QdUCLcP02ZXnqO0lZrAzNLE5b6gPq2sMi1QfvqJtGtbasm8nbJFwSBlryy+0lzycgqLiwp9bitYuHjXr7pO+rB2tm5Z708tDpRhkihPhX6NdX0E/OJznVf+2lQI47AbnfT9rj/sJXPIc7SrdcwVqaVGFqyA8TA0qewabR0TqnpdT/E+WhnNi5WjlEiCXgnuwbJmxkUXqDzeHIPzP/AzjRAqjOKbFvKiSsoSuSZOZr2Zlx+pL+KMhDtim0pVyIkBeX7p/ejMll4d99mWSvLSTXt0TReywMFoxgla8xw/GBJcFlQ8cNhf6G2ca6X/bmNxwMKjz+fBs3d+CJAbYB5bjsmwuVe3C0StmWRXrmshvbjJGybAwET8dLjasdqMy+s=
    admin-user: AgCITOFjtZZDtwktQdT7O2BALhToHKBNzVXKqGrISj3Tw0BJ9hHVQOfhKc/awEWp+saE73em6fTynVVdgb/xn5NmNUe4GZyjCALl8wIMiyb3LMA6D7Nokxg0CGCcExpAtWCIFk6No4s8oPbgN7GwNSRt7wrIc3kshLwLegdgQZGXx1Tl2ljRsUVhf2AOiO3w6Q0hVYkZ0snZrrA41sPzlaGUbQPmXh1IvrojmYtFUpORQPrjMcXM8e5Ru/CGvja+sHXXKa7pzghIJZw5hNoqWSqL7DW6SoU7dQFYWeW9OaudFwqS9Ge2ntghukdXVSB3SmbsYzmsMwFLR9brxyucPdw5eX3uO2k9epkLiDljJLBDSGi+r6D8Ak+f+VyrQoEeJfo6VmF2B0J12P2eXK4gXLTvOyHCZcrOWkWG6iVj9/TKWLeKGSLcieezffJHgCILNUFVAV11K5iFxQnnHsD4EhZmAIE5uuoe+spJgt6pVW7wS9fF0W/ZtDOdMtdyUQxysXNjeGjWDiQwWBFBD6Q+9w6GGqHHafducGb61E/fbQGatbJqu4NnuOwY5Gh+l/WRJBiwmIhVTNtxJb3hiVqJwJaNCvS8dhdkfrXad4uYr2BsVoLjWZoqjVoyF/8GM/P83W6ehridAbD6Mj4FxNs+Pux/OZFnWDjJEEQyrwRobjfMQ84btXF4yk+lsRy1e/2Hxr17MWVVAg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

