apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAR6bNxglIBdlF/QyqD1yPrV97sj6UqZoqs3haE2vDpD32++ArfbbNcwUVubZbzKtawEoN5P5BINUH63xjQAL66BjIfzO+/6HjlfsSE8NOM7bheojRBJrbC+yRYrRuFpUDKjPjQ+ECTWXyFJerGpS21KnCyhEtqitKL6KPKVfcUT5+lFRgIv5SlWr3LYyN5IXli0ape3C31oAYZ5Z+kYPtr4S8GI7DBSIcvsELE7NYn+IWbrCtPl2LkiPtEFafwgwaBmfwOIOLjwJiPYfds+8mBmxCLQ7p86VwlpQrzcufzaoRNM2BmroCWrmUaU0xQIMwJvPoK3wVomK+FtPqQznoQaRhqo6dzATGGG76mX7QYVYDIL57Af3FkE+KB07Ulvhz0GVSnrJpnfnuuTtqFE4CAb6KZrVUrPuDaX/rZsyHOpahwB4rNfOMzmJ7uCjja5tWVC5qjkzBp8obUJEMU7k5rBNTk7iv49kDCuL71fb6YRRlh5jGytuDijJ5kR8+Qj5JEoUxvZhdmFHODA8TFXA+BjnS1xvmRk3Uyb+5epB2/VuH23vkGB5hiZJfGLJkgQ6hhjWCGnWF2ut7TmNt54zfSwMdyyB9qtWdRymAWsy6DiXr0mniQgAvopKW5jDPwFFnB477NLLh82PDXQ0Zdap1s71Z2N7VBIewMxESqpcIXPnbDXgAlzMI5+JvZQo6NMKfDWcbnoP9uGA==
    admin-user: AgB73xq/LSZh+NEmiLSpPSntMaY5hIMGhqiz08Jq6yxwJ9WmDcWRBVoAWsM2hLB4w/NKLsgfmZk98POtrGQPsY+1JhZJAIJVNomNfmScGAQ4edjQ6H/J3iJe8iEpcqbEbesgau6DK9Yd3ZYyRKMRzX18H6dZawKIy8BHAFPiXmWhiDVKWNEuOMc7zCVAgWgsc0YNUT8SE/1/5T8pcNhH13wM5EXEjrpmw0r9KAQop9nSLV5ztd3X+Kvx781f4zYPnUk5Lx7A3B2D4SKtvo908IAiz429xK4so0XCg9ONTrI8ZotlK72efbeY95azi8n3PEn4jK5uY5reKlCrmc699jRwXsvwGGbP2cPOALGYfsxhr9HN1W3fJuFeMi1oBizgdI6g2m07Uc27CF32UmUBb3fPwM9JGXA5lJ8wPZJoxNEZTzJWhXH2LTD56vBYI+81x7/t5fzUeKQlI2yg6CHKtENLutoDt2kF94ZtZSJoCGsUm+DQpcXlPKC4f4NEyBEGn7rxmxmzDXrqROfDS8+DEABQ+cwE8lGe5NOIYRlv94OagIa1igsxY5BNTt98MRozqHt8fZxId06c+KafsWmSv6/ClgvuIPxzQ/yMxPMxEIyRpT+bZeZf7sjqCzjfG8ZaOICe0O9Uj5D0F5XGTBQ+mGWRv38mYVDXE6yJkU7UXSCzFAMUnzXVYPUu2hDY4s5lYNC4jqVphA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

