apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBb1RcJR2UYBy+SVJvS5qxFqAH+3HEws2ns5P+c1fIBD63sk87P6NM/NhBfBq9IzrSthML3QsEs4qos+lak/LzBUVvyJWEGjvzD9mW8CrXU3nDD1XotRJLmQ945HsKMWN69GMBNlno+SIZzyoOad7kKadrdSDkedTifrp99Auq/DvDKzhkb0/4Xa0fGpQN6NIIEf4nGj5hhKcQu2IvqVCKvFdvewtH7Ek0fqYPubly8lQcBVkUmfZKXk7ML7BqrOSSmq/Xk8udADtCyq+TK951QwX9IbHGkSpyXDRUkdWoDzSEAgCWeGltTGQNF29PBZTvJSpn/3iaDr7+hSVecx/kO33Z99Xq2WnvJXkgtwmPOvSeccDV2u1Zq6GEl4jLBp/ZRQBs91kTBcg0lmgEncRFunug4r8HVl0P3Jguv4EKwCMQ0dywpUm6yZVc0KFIGSIVPM53e1ygllut2o1okQ9VqwTEOWBo/0mPxLJBBFO2OZL0DNGrBnDyvFpk/QRQp8zEt/GljiirRv35jfpzeFECVK7Cw5XtMFE8RyIfXaKgAbZx+wwhVEpLZWvInmGVY/kiKgI4BUkXca89fo1FEH5SlCKeIliIYPGzOAxO40NVhi29c0OmeE0uuFi2F6TOLXcspsvWU77ELLefp81V1pxyV134xPSFkG86ujKLR4z4hFEo6INdudaw3YlxuLOSBLmeUEBddHWmjew==
    admin-user: AgCc8tJqqnDwaGW8S3X6uXMqpw6daeNH2WwSg6BD17E+7tfk4STVvEqzlPoEyJpV3dYwxrj53CbUOA4tm+zo2kBsBfm5GoL1YNg2ZMoVetpWEETHGnlbCwXkT/2Wozln4YJ5HfClLRGuRUqPd1+Zyzs4GohQBtW2w56L9cFMPDMR0TY39eME88ErPdJqXv1Lte+SeJYMRkURfNqsEon9eT+unaTQhf8bRuWfb54Bto1tYlAerTqMYU4GByyjv5uRfdF39Fr6FnVU7CsIucZD01ukU7YFpws8qfDno9tOQv9DvixzQe5Fkylmu0v07izpFCTwLk8x77O5zBaJXBTxl2XC4v0KTEUlOut/CaQgXaY/T9unQTUzJXPQP2rLHf2H9avUIAJ/jBjvGqu7MSC84Gmv/br1ykNfWtlCwxraq1qACdgYPcP6yx2OjDYiamcF3IYmLiQ/9RkiuT7SjH4agjq7Ut0MY2Q2SAaU7yQupwhlIzDOmuwIRnth5CFK78gLk3izm7hJm4VtQ2h6nGTISNJYptn8d54XrnLF26MUn47RWb0N5vS71f0U07JfbzkDt8CYNtgGMUQbP/28N0cJsnPnSgpDmSiRkraU0Ti5MHngpxdx6MeQ1C15RqG3rn+bcnTsmalhscyHBZx+LH4vvc+x3qDZiMPjixWx9TRhnWKEn2mZHnwzdtYrne4uYn2ndcIjHHhztw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

