apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCXvfZ0WnXypS4MZuU7iIrChbHdHs1+6+LSreeH0b5h/5bVANVkTPQc3pOj4TxWial3EJbOgmHDTVSbUmxllut25b/LVeVtS5L4hpQNL/QoRZgxi5/60Qusjyanqm+j19lUA2mwRnkpGGFQniTNV1Zet0O9QenzRvdVby/1GithU8WOdjh4eshrNI7f2fz2tYFUAOjbt3cPLnNNesQjhPQHfhiRJn7wux0Jm31+SxBismwGmyLPcUqQ2kfcw8w1yHL0qPY3HE+jc1OuYJRNS48+YE7PK0fnbkoyponp0EY6TLdKuRF1FJ+q6443Pzi9tpoOkgo3X41BXCkFLo1LzF6UqIrHsK4Pq0lTxZpJsJEnjLCLO5quung402MLBW5vzG3DGZ6Bmp+2o01V5AxwcY49HmU8YGvL6fdgAM3eOqQ2is3JsLm0J0f5Aak/PaXL0VRLrMWJt98gl+48xqSGsbuYmq8W51Ze8vVm/6wyzNzBPW305t/sTOfqxC8XQN5ydNkkr/QfhbrTL5wPJGWbJ4d1Gw2PcKnw9S++9XqJ+i+IjIYgGNkF3dajkj5woLoxxfuu20C2FSc87b/4/tE0Lym9i/X70CL9W7BZRITW0oGRtsO/k5++BRCJftBUvdcX7ZVAl6JwXsebEYuoHMTru1gHZeraaTXnfqu+G3jwY0kT/xbJ583YW6C/8APFDTiy3JpVMHgE5fkq6Q==
    admin-user: AgBBaPt8wM5/SzUxLvkBPqnGgBvi7MVYoYBH1RbQq9Pq78XgrhwPfu566kCfiDLBQ02MuN1WQ3+Vdrn+6vwxGF3VfzUhak7NenG+j1hqL/PNDztVYcifgf2w4ACfUCQSBtIPqdJr8TUsMHcYd9WFVhE0IQTS9x+TXUi/K3d/rDE5QK5YyyvrIkN9JQIhlqYcCzZnCo2H1BgbyyW+zpK6OmyHuPt7nbNfGk9tZse6qd0slx76f3EcvzTaV+Hmbl12nBY5UxfY5l+PrX/9s7qXLjBzKrAx24+aEd/sYzO2HXOjbZQtJ0b4paDP7y16pLD6qB0rBAEnN1sotYqsbN5pK4A8cingMVCU5uCD9du8JErio2kZ2cTAfK978k7t4rLDYSNjEDivlajZmaqKSRG4yqUXEdbVN6sCtNIZ2FI26otorr0zklkyfTiIw5YxFGdbVP11RQfJJln4vpp5+roRAGjJoZG8pTjHkD741RVaCBKGK6QwMtxuhE0MuCbcRfQRJKINzAnnrshYftim+qbAlvByZE/ewul28a1WK3lonJIKnqny/gp/vWrfkp+Y5cNsPGFrsFS1v0jYx+3MMA5sPSpOzT0aewLl6nmo8DFx59Ewvf5WP6Jj4R98iLouD1VitfSN+C5jPfAwgJVn0IwhPdrYV4OefQYsW8SGOSUqyLKQIaEl4V91X0/fxB+TLBWBrtgCggEHEA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

