apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kiali
  namespace: monitoring
spec:
  encryptedData:
    passphrase: AgCrbNCLwKlY97xvLgUOj0zfEoBX52+uJnbyJRiS3CmmdkR+afm8B/ouKL86kk7J0zVz/zjBn9YH2WXgMmfkZxkjxTHRBjRtzZoP3UPsTpHqE0KM6mzDzd0fXlPaSbmetSlMWhrSUwxrAkluZd9GRW2rGbGHpZ5VvkpKM+fnh8ewPlRBd46KqnhK11J2hMXtw9qZK+YTpgJ+K20RjKg97cisr2P3TBvu8f6svVb4dv84cips2xCG2/xV2jIqGnlfqgp0/k/EGfg8UOXj74dPRTwsu0cP6ULPQtcdVyG5qldqU0xgl9ASZxnALxW13hzEcHMjVl81oKn97ywhVGG5WWLjBmRgldlaK0ZrbZVNuuAwUKZohfBpgtuoJL7MWWGL3UqQWImhfYlsMLMScHJlidXLA1mWV6gwnEAeWJOVn+vz06+2eGUya41/9etXsdjoUNcSVyb+Bbalry7sRIXPQpRzla+NpcGPkwcJQiomgtHbzwnShtJLaF8htIkob6Qq7dkzJGrkyieccRc2wWZvGJnGo9Xqgy04GZ/fnX2Dtpdz7c6Rs2ZqnSQETYR9mRjObzXeqV8y7kkATltC3dvRwXwPQcm7KziJLIz7fVOBqzqtA15gGfms/yoN+Bxd6ACtYONdkPaNWqaQCFbvGaSoHWK/tX5K9dI/AbWrQW++yXoYgFoaExb3xCDR8AuI1FeZNa6/lcsIUw==
    username: AgBUDIsnzwSjoJF0b9LBwoN9yOOCSINcM24aPUkohVxNeQTvuNctW9i2f4snl7NtLAHdOmT/I+sd1O7gKltZnOlektUogifqaBXghgXzFFl36LVggAVTo+ovf90MUg9P+xp3pGZ4hflLy+cPa+7NDYsNsohwtiU/EwrzLa7kldjqWAAX1/uhS8WxXoxJ/oa0K9LzX4JHhYhNluJsFFYpDs2dcwCe1EhASRUGY8mgdy6VcGGqgncALv4DPb8YGaClGSLJt7agdKoX05IlbeI23nDvlAdWRdQ/2tyZZ6mS1dCWYNMiDHhLCaYZFppn1rOQ9O/DF4USkhVVmS3NRoqrcVDwPrhdXtXQfCtEKSLIUamM6hDQxWuFb/UPPRr1h9fJpvro/5fiIJR9wrJDrHhF7Px9hnmrlcI/xTlR0nZilFtfR2CSmEU3W3qdIOBQEHkP7B56ODEbpps2KN8PD/2dq4UKuJwPbGIkhRSRyFonsYwcRSPRgCduatTQEiMJ4w4LWdQqHqcZhsuqJQ9s0+teVx26bBGPBtqCeCjGKpeqchc62wzrg/w+hib36oUQQV5cAOMqTZDmfN5L1ALorpXo+O5AKA8uzuHexsKPNNb8fSdXab9c47l8SOCQ50redEs3SPyIT9zVKPBE6WAkY7AOYqrMuGDY58UqMiWMd1jHaSpv5a7TEKwPDaQTKsyQBAjbtgUvxi6xFA==
  template:
    metadata:
      creationTimestamp: null
      name: kiali
      namespace: monitoring

