resources:
  - ../../../bases/rbac
  - ../../../bases/tooling/cert-manager
  - ../../../bases/istio/core
  - ../../../bases/istio/1.6.5
  - ../../../bases/tooling/monitoring
  - ../../../bases/tooling/logging
  - ../../../bases/tooling/nginx-ingress
  - certificates
  - external-dns-credentials.yaml
  - grafana-admin-credentials.yaml
  - kiali.yaml
  - external-dns

# patches:
#   - target:
#       kind: Service
#       name: internal-ingressgateway
#     patch: |-
#       - op: add
#         path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
#         value: istio-internal.main.clusters-dev.internal
#   - target:
#       kind: Service
#       name: istio-ingressgateway
#     patch: |-
#       - op: add
#         path: /metadata/annotations
#         value:
#           external-dns.alpha.kubernetes.io/hostname: istio.main.kubechamp.gq

patchesStrategicMerge:
  - patch-hostnames.yaml
  - patch-promtail.yaml
