---
########################################
########### Nginx Controller
########################################
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: nginx-ingress
spec:
  values:
    controller:
      service:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: nginx.kubechamp.internal
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-lab-main
---
########################################
########### Istio
########################################
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: istio.main.kubechamp.gq
---
apiVersion: v1
kind: Service
metadata:
  name: internal-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: istio.main.kubechamp.internal
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-lab-main
---
########################################
########### Loki
########################################
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: loki.main.kubechamp.internal
        external-dns.alpha.kubernetes.io/target: istio.main.kubechamp.internal
      hosts:
        - host: loki.main.kubechamp.internal
          paths:
            - /*
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local