---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  values:
    loki:
      serviceName: hello-loki.kubechamp.internal
      serviceScheme: https
      # servicePort: 443