---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  values:
    loki:
      serviceName: loki.main.kubechamp.internal
      serviceScheme: https
      # servicePort: 3100