---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  values:
    loki:
      serviceName: loki
      serviceScheme: http
    pipelineStages:
      - tenant:
          source: "1"