resources:
  - ../../../../../bases/certificate

namespace: cert-manager

patches:
  - target:
      kind: HelmRelease
      name: default-cert
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-ingress-cert

patchesStrategicMerge:
  - patch-cert.yaml