bases:
  - ../bases/open-policy-agent
  - ../bases/cert-manager

configMapGenerator:
- name: istio
  namespace: opa
  files:
  - policies/istio.rego

generatorOptions:
  disableNameSuffixHash: true
  labels:
    openpolicyagent.org/policy: rego
