resources:
  # - rbac.yaml
  - ../../../bases/team-default
  - ../../../bases/flux

namespace: team1

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: team1

- target:
    kind: ServiceAccount
  patch: |-
    - op: replace
      path: /metadata/name
      value: team1

- target:
    kind: RoleBinding
    name: read-pods
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: system:serviceaccounts:team1

patchesStrategicMerge:
- patch-flux.yaml
