bases:
  - ../../../bases/team-default
  - ../../../bases/flux

namespace: team-1

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-1

patchesStrategicMerge:
- patch-role-binding.yaml
- patch-flux.yaml
