bases:
  - ../../../bases/team-default

namespace: team-1

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: team-1
  target:
    kind: Namespace
- patch: |-
    - op: replace
      path: /subjects/0/name
      value: system:serviceaccounts:team-1
  target:
    kind: RoleBinding
    name: read-pods
