apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
spec:
  values:
    git:
      url: git@github.com:kube-champ/fluxcd-multi-tenancy-team1
      # path: "deployment"
      pollInterval: "1m"
    allowedNamespaces:
      - team1
    serviceAccount:
      # create: false
      name: team1
