apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
spec:
  values:
    git:
      url: git@github.com:kube-champ/fluxcd-multi-tenancy-team1
      path: "kustomization.yaml"
    allowedNamespaces:
      - team1
    serviceAccount:
      create: create
      name: flux-team1
