apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-internal
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-internal.yaml: AgAVBaWfUR3wNaXQefTwgvejVMB8stNl/RA4U/N2vxwmagH8/0Aq/h65zeCd6Fnl4bM8L7jrNv4Sx1+lgzhtzJPvdyj4YH1yjnH3YBYmf73334jv57tDyD65fb+nsHEFogab+zd98ce/WKkz2RtVrB7kECuRehdPwj6mjKYWcAuuf/OS8u80MIQRUInGJ/4yi04A4WbjAs27RS3n645sWNq/eB945mBtaLJdoWY70bLcskmrd3iRU1aJfp4JPJtIXGpf33m8Y7nn9flsBsbTESd4v5HHYobB8el/j9YVM9i48KfhT+04QsD0cVZnmaNl5c8no/XWtA/bADbUViqAQxetSg2rtvuoFqTEIOM6WzSbYIfPQfBYSy6BNyVS6uduGu9rLJad6oOmBRM/ElGC+4s93TPrZjemhKolgmEOlumnHCSt7PViYzx6e6Sm5ow19mylmpe/2wwHw0FZnsmU4B/Ftfso2iOjZ57Hms6w5N6/8fg+kHFzKnihZkdaA+EAnHh71FXr2UQ7YvDnOgMWP6hFUpp10alQL1aqiYJSJ4CsFvRdEhCDLvqvmmTLC9JaNpViXcan7Ug59tC4XuGOlA1BoeCy4Z2kdIYRsh9z4J6OBKbdEJqRXNbe3BDZQGYnaLzQpEjan+fyg4vMC4V6BgdeMjYTlY6ODAqro0WRJ2zvEF+pDjf8UZvxNLf4UfprcPJXGFFcrDigtNkf6OkzKV5yjsvP4fCiI1ADkWsqc/hAORIgmc0p+6cKSEaa0T8Emx8CuRN2CpDYxTC5WLDv23lzprJ/+C9tsW7vQDZSMi++AMpXXGQRpicgr//oaADE/2yUXcHnSPZd4x+U82gW879D9sAoMtQM845GaiPsmTAs7O0xeafk1U5rs0PCzL6tJp/C8yn7h1OWAaFS5oA9MBFIR6ZVR1KkwejHV3o5XkjTCHmdj/Q4dJGVnBT8VeqHZktrZumiS9oGzep2iDzfamWUa8SpvJoUzdXAuglOB6cMcFgZdQKeNqJCiJvl/g3QcaUi/0zuFb5R0yijOfpAFNaESYP/8NbY+a9/sC0stMcXfbA/KIJ5diFxvwsPeB8343X1HLulHQ6P+lRlSVNMXprHUPXiWIo+cq3x1GXSLENA+ocyI3Jt6cGXoQGmO+RaghUaZOIDmVX5QDkpR6jic3aa3qJkNByjNH+1QCX74iYM033UTkw66A36N1b7UfdMoMKKwmkORdvRTXScatVFe5iK+YVKq0813K53jxlt2a+QdLRxD0UwteKVXBwGyc+v5dPfc6FIcz35Kpbh00vPZLC8n8c1OZZ6hX0OND5u2pvMUArHBtHsAz7jLg6V00VWkgTFYZDGQT2A3qHJxch6TIoAVin08ESsKHnMlgwdNC+yle5DQI1S/QPZs+5GAAHjb/EmcNp10A==
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-internal
      namespace: external-dns

