apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-internal
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-internal.yaml: AgDXlzhjFnpRNLBC148Hx+55YMGigbugshtbiQsK0idA6/AnZjcG7yaY9WRSTTqluOZ5hMMxheFCHyHU9OYhIuX2nTQs+LXXaveZ92uy63tGbD4pxFm/CE4m4LeAD9af2yEnxD8uFW364jlFL9gUrhjBOLMRFzKUTGn9OFJ40IeR9kICQkFqlgIoOoNciw7nCdogGXnxjft2oLtrhyS81jE1sW+XUKpaenp/v5J8o5Rr9VSCuvwmvmNGnrH7Bvl8ZgDVkX99IWQHOoO8ruM472N/UyjPcUrchIUFJ0CHV9R9GCVk45Azzan0A4vxqojSuMyE1QNreOEtK0k0pyqRAGiGDsJx4R0GT/mln3r0K9x4RRTtgeh+J6I7gsFE32lHcwRwMEz72EF63a5Xktf2IX/M2oDOv7Y5AnpA6afYgy5qbcZlq+/WsOuNKmSw3A0Ws9GkXG2pdMFvZ6JpJWeFwF2JRIO8LInwhb5UFIZV6aR5/aoE435TMIjAXjLJcW3X8ob6NKPs03IyUARdZrv7mGIqVNt+Asc4zJvF/w6V6GC8ZTVw5TyOnYpfdM/lU0hWH2dGMqCELwUytr2Fn1qJTqw723M+Ns4dpFsEQLTKUpj51G3nV3UqS5WgLAGyNr2I0FAO/p6Qbu9zCBrVexc1n7pKHR+AAii+Wed7HqIC2czNitpkeCn4zr3dopld4oSPmIADBYnAwd7dNDKKr+gtYKPjM+p7P0QOipNpd4I3ilN00wMFuhWef/foes16T9AisCUF9O30gTXYabk7ajXZGWBenyOaXF5PRtF9If+nn3kcCXqr2/8cHb1qyXpX+RolmHt7COKYcMQDaK4OQLZTBuUoktZ7LLemEcX63588IAmDh1QWw4J2P91TRVxmfLL8JM1NT65tYEIZ4UE37N3gZ/J5RfLu7+i7boKalpDfiUkXg5zYil0snKWX/0IQMjk4qKNyOtvjVDmYU7g/35BPKlXb9D2qeG/KtTwv6MPau0OuTb/IksUabjLj2g8KPDoqEkNrFB9vCbN0ebQPh5JWioLxwDABIfZHpPWYlQtuCRaooCQbQ4EWT+q6edNx4ggeB4cER4Zl17XatnbnXxXR2zHIAO3OludTjP8wX3VGu86NBTYWOo8WH5eIuaddf1GJ4i3FksOrtTyw7IZsLvQPryGmQCu+P46Bnz/cMybf76xpcXxfk6WzituszYSfG+DXe9UHcKVMv3L/X8AQf29tNBsiK/IBef21K/0ycgfrrdl/EtSTre8Kc2BoWfQq2oKcfzYlXriiwDxqSi9tpkgvImBjXK2XNwBfxyaDztuxCAz5X6VPiZx5mJOL6BTajLMuIV+m3ru5X8fonCBmPvmfuB3Eg31DikgiWIVNmGmzvpuz4mQrbQvchFpDDr7kTq3ntQxYE2sCyw==
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-internal
      namespace: external-dns

