apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-internal
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-internal.yaml: AgB+RrQufYORr6sdcCwqwO62ZIq+KBo5KL2R4FkKFVbGGRXh9Bi22rFCMWuLfl0vAW0wflxu6BrzyIjrFdsMQ5B7IK/G4kqgwrF/OVn+bOXi66t/OpoxkIiJwbln7IUUNlTH/UIEh798i4PyP4fO1ts5WvGjzrh2sXcI1P0B32yhl4SdUPQETWugbkYOS9LgO5QHXHonHOgSdwr+cC1KtlQYOQ4PU9QkN7X5yNkMwhxWnHXdVLp4jZbdHZowiDzzbZR+D50xnL4Rtn3hearccjKhsMJTaLOxP3TuUlPkTY5X7a4JAjajVAY6Aot9YaeQk2P6AJv+Qrm9RjZE0oWKB+GikCMTtRtRsiTLMOpIHR7roPz476/fm1j5lQs0SuvZWi5A75ge806tZAEeYNEg7pgUd5qaL5EyJejZqywg8Ap5hv31P4PH2wkNgnu1mCqcIKQSpqg9aJ0R1td3hjtFYW9oaMbHze9/0wZ20rPad1bINXrhejTkyRpMzZu5jKaqXZyHcmg20MsI6M0iCdRJjxyGMdPu3cVy7pspLQZeSrRcoIeyEErF+z7SSOve0q/1qDAa3CxPlQEHF0ix1JmLwP5UH3yydPrrUCQKojWCJrSydwk5ASWWIlIfQKp4aYHJV/36VYpLrfLx+2MV8hi+8CKYEDvyZnYw+yh1LrUnovjxss6vanCbDkqmfKGI84Ead0zSLBUnnifgy44aht8ZWIfJdRune66AFsBjSlJClzKhU70ynqpR9Z02Zi1Rv2920AL/YriVOSlNSYZz/y6a2l9FknuVMbeAYp9FcohENjoyf2gow0Zz1NuzlsTcNER2c70sqmCjTASmhoT0mfHRoKCoK17H/TkMgwu9O1QKVTvvfTiJmDe9Zoo8E9xVWk34GU68o3+lg7sQyGtsVpVlGmiTdhz6+z98furrwdqYVZs4dQJU6IzaexvvXXTR1VC0w9VurGNKyj+3PEAbQ3Exqw3c8X9EVP5wNe38VE0WaTKKIBXB2KhU2fNJuUgwbX8sNuMCHr9XBAj60GgAn25KNaQbXAiWNAotJbpF7aoyZ5NUBYy0hp7tBy7uTLIxkic9Ur+pYzsVhvCJLamQALMiLOQFM0tR9m+RJ5uwk253acVGu4T2C8Z26CLs4afR/7qSS/urvz9HQ5k9TL4sezZb75PwTYCMzqBF/aEIRtgYyx2CxSNfGDC4J5TqIGAGvjAaBtcB2XVlqq2LPcPHtTLRtHWjzG+wIP/AD7Bxg9euJTPLmM3XLg4MrShOB3luAjvvsN3DB1lIM+9lvRCcVVwKZT7m3kiVCwNyRp3ib6A+xp/aUE6T3rR+Rv4Jvjg1X30AN8jl69IoU7nkXkXiSwIljSdbG6BFIhr0rxOUBBIyTVh3sUKilULcKspynukca2MuGnwdGXjyeQ==
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-internal
      namespace: external-dns

