apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-internal
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-internal.yaml: AgBAmwkLqPTI9NdONXqB0CkRj3HDiKWjpqGG1WmT/59NZ5C97Tjtfv10Fql8gGpzuS3uJrwVHZLyKq31VVkFrKKQz3aw3q/EuqyN5jToVj0+5C/yifU/PW7JXjyDELC2ldxUy8Cz0P3NWG8T+hWKY4T2DHOYKSD0CqMDFEIt2He/M9cK1iGvOhw2MK9VbHdUDD4UdPt9ThByvawC8ylc/h1SpI36pArsdzUVbx7Yh++pgvG1fSngnEj4YzE2gINFs4TeyYx+179ZzmV0J3kLj0lxBSAZ9fvQNcrnLxNVkYuOrRsP3WLCtqeZsZGeZJ+FHzP/jkiLe54FQE108iYpBqcsAaPufmw+K/WLK9AZ71+3/NkaDy44I+JBi0hOhiYRszlFVh5xRX51Lj8+tarZZQxZdj0aM0zUZ60m/YeFnrcfdaUvU+Pws5tJTMwMmTVGi/t+EjfGcM1SGBemyLicjArPjDrAkycwJASNWUwPbZPKuFctsfnDEeHFIZLAQUnR21a/io8CnSal9+HTvnsdAJgsc7vhtHWyL3sETpF9xMUbofI93VzbA0qbtShvSuMK6yAeI7hcCZjSOghP0EbsDZN0Nt6S6Z0vGCN8Fma/wb04OW0gf0piJTIO4Ad2mMEAIecDcViaVB2kBx6kO3yyZRoq/KY0CLlMl8qw1HYiOASDfRrxL5jVz7IusaO7ySyTEFnj5Z/gXy0iuQKcWSF71Jb/PnjlsLQoPbFhjUX2/mvbloAsYCDb8igMQkXQ5mQtWA/Av5CHj4n1DnE9gVzTHiKnMhLNSBN/3aCnsrwASKCFaBBikpYtNF48finnTi4hYTXazIVvp18N5nMQcjtlUOfzMYRf4WnU4urLcNRaYDmBFIVtuCKH13I9+J0RbgXphD8W1SxiblbC+IemDuVWNCA7OXvKeckmdQ3UxmhDP+pcUAnA1IDsTeMDl3v/M0DiHPWe+Xul22uUs9LkNT1cjSkwKw8DPmZ006j2SVMBUpi3LCVi5cp5c+yuqLV4F8Hrhu0ttqt3iHP60G3GR4C4w96Iydc3ppj4bFL+bXOWOl8hbhsKKvsVMRfsreApD0Jewv712ku+d5QMYx7VHefH/g2ow+X0avxZqx7MEKVoXaLQiaIrQh46e9uz/CS8j9cH4Y+ea5QFJemxgQ1cCHlG9pGmUYflXpkYAnh83nfe4Vq2LPMAK/m9ClwkyJJUg9mUUkbInazH6arksfc14g5CeMc6MzI+FOoozovZhNflJAnor9ANYaSV5fchkFVWrAkf+pwHXl8vme2z7FFU5T6nd+XOBvPEO5L7ANMNBAs6UZrxZMakKwL8/fCl+Ek6e2TGvkINJIpopqULsxA3yAFuGD+X+Bgs1DJBmyh1Q9aq07dvlY/LOxYVg0CL6brtqnFH9LC5jMRtNw==
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-internal
      namespace: external-dns

