apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-lb-internal
  namespace: external-dns
spec:
  encryptedData:
    svc-lb-internal.yaml: AgCXfGEcJexe4BojGuEMW+gHuJ7f//uKF3RR74izarcAnqPshSXNYUGCzFiZzElTvqN6kot15sm0xQwbxmI/VRQfNEDCrUBlRwN5QsRFU0wNwtHOHHKUyb0/O/pf6IXF6IppwFtYPRATHzj1zkitPAP8ZRnw/ys6XHors/mWHZa5zyHtyeI4PUIuNL4bIhZq9kmnpVOg5qCCOVwilKtWFUYmG00BQ+cRdg60KtucaYryHh1YU6cM06C3MFZK/F7svKkW74QZUbtQWgeNZOaCBUxOOOIvwkg3/Mw1cbS5V9ToOM92W65zgPCsNLyKjnpgxwY/SAjsDnnvT3eficLAHVdNTth56pnfCALHVHB/EnWwRLIRXdbMaKprP7lJTkmL3J7KqH2XrkbPWbiXsMbP986vXoH37kXy5MjYdTeMnpIgHgN+Q+BVmmTPbVMw9NwsyKN92WDAXKla6gOMpkglP6nDi0hfh3y4NF87Cm0JT+oZot9m/5xbovdLioOHM4CNwrLDtPn4v7wsJxHUmKR8fmiL1BII5YsxuJX00s3GY9idbeQXays21h+Qqe6N2j6Oc6ohjKZwH9YmxpyEJA8VIpDa5xKz/n7zorgZTJYdcPt+HbM2D0ifSbdj8u2GjoievickHpNeCg6dbELlxQW2DEqF+BUGwks8QdJBxqXpOF/ZFviKL2DheLjJfk6vio1TomHAd5S+J8m9C6mZnPcvG2nx3EN+FPEMpd3l2arRurNQadm9i7Y6iy+7Fewg6TtsMSkUqsbfWm0v2cfM1mWwsKemZpkDVf5g6KVw1BXhOt7uxkAR6mWfJyAUXUCdQw8uq2QpTHTUntwz4NDsU8N9eJRwbmn/J7k+9PDGTQaWll5m1RqiCT4e6ldm0K87LvbF0VyHxjWVNSSA0hP387h0/cQJdFLLOwbBOTpim4yorS3ThjLY7DcVuNmXN0HN907CmH9IaDcJtx+1GXR11DlCfPEu2aLztTXxsxuwvpY0Zu5ASOzq3REUuC/AEUx/sulQ2eQVHgZyX9DGnlDyFWMf4sANRWLJ4rdWywMqM+3w+0CqAmU0wYZpzH+UmObP8oTiLLj497EXX8LoelYo6Wa4DyBXLJhwRbog+IH/Cq7Q7rKsig0ERlVBcWwyA4LDhAl4k2SAFm11D5wFV1CVDz3DPwKs/thvfxBpCTAP4RjZt7auENtnDHuSTma9RV9pLQFtn0Nh82X+rHgISJiwfrjG8kJhmW7IDOXBivgmP+ekGijUZsBU/7GKmVBdsiAIO/bEdf7K6Fx78iXhBmwkNLFJPOjbFi2gKnDuTHYA1hcL/Z1uyoi3UTWiw5RyeZm73ev6OBII/n06nbZmORA6Jw0mpQeNDmFXI6NqJxf+fbhNzD2NuezI4sJNVseYzgIbabv3gRhKqkECxw==
  template:
    metadata:
      creationTimestamp: null
      name: svc-lb-internal
      namespace: external-dns

