---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: false
    prometheus:
      enabled: false
  components:
    cni:
      enabled: true
      namespace: kube-system
    egressGateways:
      - enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: istio.kubechamp.gq
      - name: internal-ingressgateway
        enabled: true
        label:
          istio: internal-ingressgateway
          app: internal-istio-ingressgateway
        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: istio.kubechamp.internal
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-demo-main
  hub: docker.io/istio
  values:
    global:
      istioNamespace: istio-system  # TODO remove, it is the default
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      controlPlaneSecurityEnabled: true  # TODO remove, it is the default