---
## docs: using values from secrets: https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/
## docs: generate the sealedSecret value: https://github.com/fluxcd/helm-operator-get-started#managing-kubernetes-secrets
## Charts here: https://github.com/bitnami/charts/tree/master/bitnami
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: PLACEHOLDER
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: "3.3.0"
  values:
    provider: PLACEHOLDER
    sources:
      - service
    image:
      registry: docker.io
      repository: bitnami/external-dns
      tag: 0.7.3-debian-10-r11
    rbac:
      serviceAccountName: external-dns
    registry: "txt"
    txtPrefix: "txt."
    policy: sync
    logLevel: info
  valuesFrom:
  - secretKeyRef:
      name: PLACEHOLDER
      namespace: external-dns
      key: PLACEHOLDER.yaml
      optional: true
