---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
spec:
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: "1.3.0"
  values:
    allowedNamespaces:
      - PLACEHOLDER
    serviceAccount:
      create: false
      name: default
