---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch-master
  namespace: logging
spec:
  releaseName: elasticsearch-master
  values:
    clusterName: "elasticsearch"
    nodeGroup: "master"

    roles:
      master: "true"
      ingest: "false"
      data: "false"

    replicas: 3

    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "standard"
      resources:
        requests:
          storage: 4Gi